version: "3.7"
services:
    monitor:
        image: golang:alpine
        expose: 
            - 8080
        ports:
            - 8080:8080
        volumes:
            - ./monitor/build/monitor:/app/monitor
            - ./monitor/config.yml:/app/config.yml
        command: /app/monitor --config=/app/config.yml

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes: 
            # https://prometheus.io/docs/prometheus/latest/installation/#using-docker
            - ./prometheus/:/etc/prometheus/
