
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090
  
  - job_name: k8s-services
    scrape_interval: 10s
    kubernetes_sd_configs:
    - role: service
      namespaces:
        names:
          - maker-monitor
